name: mindle
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.7
  google_fonts: ^6.1.0
  intl: ^0.19.0
  table_calendar: ^3.1.3
  material_design_icons_flutter: ^7.0.7296
  go_router: ^13.2.0
  flutter_riverpod: ^2.4.9
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  image_picker: ^1.0.7
  flutter_secure_storage: ^9.0.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  awesome_notifications: ^0.8.0
  fl_chart: ^0.70.2
  share_plus: ^10.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png

  fonts:
    - family: Nordique
      fonts:
        - asset: assets/fonts/font2.ttf
    - family: Yaro
      fonts:
        - asset: assets/fonts/font3.ttf